export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_USER_FAIL = "LOGIN_USER_FAIL";

export const ADD_NEW_LINE_TO_LIST = "ADD_NEW_LINE_TO_LIST"
export const REMOVE_LAST_LINE_FROM_LIST = "REMOVE_LAST_LINE_FROM_LIST"
export const RESET_LIST_NEW_LINES = "RESET_LIST_NEW_LINES"
export const GET_OPTIONS_SELECTED_FORM = "GET_OPTIONS_SELECTED_FORM"
export const REMOVE_METHOD_AND_CHANGE_NEW_LIST = "REMOVE_METHOD_AND_CHANGE_NEW_LIST"


export const GET_EXERCISE = "GET_EXERCISE"
export const SET_LIST_PROPOSITONS = "SET_LIST_PROPOSITONS"

export const ADD_NEW_LINES_TO_LIST = "ADD_NEW_LINES_TO_LIST"
export const CREATE_SESSION_EXERCISE = "CREATE_SESSION_EXERCISE"

