export const Caracteres = {
    group1: [
      { data: "∼" },
      { data: "∧" },
      { data: "∨" },
      { data: "→" },
      { data: "↔" },
      { data: "," },
      { data: "∀" },
      { data: "∃" },
      { data: "(" },
      { data: ")" },
    ],
    group2: [
      { data: "a" },
      { data: "b" },
      { data: "c" },
      { data: "d" },
      { data: "e" },
    ],
    group3: [
      { data: "m" },
      { data: "n" },
      { data: "o" },
      { data: "p" },
      { data: "q" },
      { data: "r" },
      { data: "s" },
      { data: "t" },
      { data: "u" },
      { data: "⊤" },
      { data: "⊥" },
    ],
    group4: [
      { data: "x" },
      { data: "y" },
    ],
  };